bwFinaleVeterinaria/Models/HomeView.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace bwFinaleVeterinaria.Models
{
    public class HomeView
    {
        public IEnumerable<RescueAdmission> RescueAdmissions { get; set; }
        public Employee Employee { get; set; }
    }
}

bwFinaleVeterinaria/Controllers/ApiController.cs
using bwFinaleVeterinaria.Models;
using System;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;


namespace bwFinaleVeterinaria.Controllers
{

    [Authorize(Roles = "Pharmacist, Doctor")]
    public class ApiController : Controller
    {
        private VeterinariaDbContext db = new VeterinariaDbContext();


        public JsonResult GetActiveAdmissions()
        {
            var strayPets = db.Pets
             .Where(p => p.RescueAdmissions.Any(ra => ra.EndAdmissionDate == null))
             .Select(p => new
             {
                 Pet = new
                 {
                     p.Id,
                     p.Name,
                     p.Type,
                     p.CoatColor,
                     p.Microchip
                 },
                 RescueAdmission = p.RescueAdmissions
                     .Where(ra => ra.EndAdmissionDate == null)
                     .Select(ra => new
                     {
                         ra.Id,
                         ra.AdmissionDate,
                         ra.PetImageUrl,
                         ra.Price
                     })
                     .FirstOrDefault()
             })
             .ToList();

            return Json(strayPets, JsonRequestBehavior.AllowGet);
        }

        // Metodo Asincrono per recuperare le visite in Examination
        public ActionResult GetAnimalHistory(int petId)
        {
            var animal = db.Pets.Include(p => p.Examinations).SingleOrDefault(p => p.Id == petId);
            if (animal == null)
            {
                return HttpNotFound();
            }

            return PartialView("~/Views/Doctor/_AnimalHistoryPartial.cshtml", animal.Examinations.OrderByDescending(e => e.ExaminationDate));
        }


        // POST: Pharmacist/SearchProduct
        [HttpPost]
        public async Task<ActionResult> SearchProduct(string productName)
        {
            var product = await db.Products
                .Include(p => p.Cabinets)
                .Include(p => p.Cabinets.Select(c => c.Drawer))
                .FirstOrDefaultAsync(p => p.Name == productName);

            if (product == null)
            {
                return PartialView("~/Views/Pharmacist/_ProductSearchResults.cshtml", null);
            }

            return PartialView("~/Views/Pharmacist/_ProductSearchResults.cshtml", product);
        }

        // POST: Pharmacist/SearchByFiscalCode
        [HttpPost]
        public async Task<ActionResult> SearchByFiscalCode(string fiscalCode)
        {
            var sales = await db.Sales
                .Include(s => s.Owner)
                .Where(s => s.Owner.FiscalCode == fiscalCode)
                .ToListAsync();

            return PartialView("~/Views/Pharmacist/_FiscalCodeSearchResults.cshtml", sales);
        }

        // POST: Pharmacist/SearchByDate
        [HttpPost]
        public async Task<ActionResult> SearchByDate(DateTime saleDate)
        {
            var sales = await db.Sales
                .Where(s => DbFunctions.TruncateTime(s.SaleDate) == saleDate.Date)
                .ToListAsync();

            return PartialView("~/Views/Pharmacist/_DateSearchResults.cshtml", sales);
        }

        [AllowAnonymous]
        public ActionResult GetPetByMicrochip(string microchip)
        {
            var pet = db.Pets.Where(p => p.Microchip == microchip).Select(p => new
            {
                p.Name,
                p.Microchip,
                AdmissionInfo = db.RescueAdmissions.Where(ra => ra.PetId == p.Id).Select(ra => new
                {
                    ra.PetImageUrl,
                    ra.AdmissionDate
                }).FirstOrDefault()
            }).FirstOrDefault();

            if (pet != null)
            {
                return Json(new { success = true, pet = pet }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { success = false }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

bwFinaleVeterinaria/Controllers/AuthController.cs
using bwFinaleVeterinaria.Models;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;


namespace bwFinaleVeterinaria.Controllers
{
    public class AuthController : Controller
    {
        private VeterinariaDbContext db = new VeterinariaDbContext();


        [HttpPost]
        public ActionResult Login(HomeView utente)
        {
            if (ModelState.IsValid)
            {
                var user = db.Employees.Where(u => u.Username == utente.Employee.Username && u.Password == utente.Employee.Password).FirstOrDefault();

                if (user != null)
                {
                    FormsAuthentication.SetAuthCookie(user.Id.ToString(), true);

                    if (user.RoleId == 1)
                    {
                        return RedirectToAction("Index", "Doctor");
                    }
                    else if (user.RoleId == 2)
                    {
                        return RedirectToAction("ProductsList", "Pharmacist");
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "Ruolo non autorizzato.";
                        return RedirectToAction("Index", "Home");
                    }
                }
                else
                {
                    TempData["ErrorMessage"] = "Username o password non validi.";
                    return RedirectToAction("Index", "Home");
                }
            }
            return RedirectToAction("Index", "Home", utente);
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Index", "Home");
        }
    }
}

bwFinaleVeterinaria/Controllers/HomeController.cs
using bwFinaleVeterinaria.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bwFinaleVeterinaria.Controllers
{
    public class HomeController : Controller
    {
        private VeterinariaDbContext db = new VeterinariaDbContext();
        //Get: Lista ricoveri
        public ActionResult Index()
        {
            if (HttpContext.User.IsInRole("Doctor"))
            {
                return RedirectToAction("Index", "Doctor");
            }
            if (HttpContext.User.IsInRole("Pharmacist"))
            {
                return RedirectToAction("ProductsList", "Pharmacist");
            }
            var viewModel = new HomeView
            {
                RescueAdmissions = db.RescueAdmissions.ToList(),
                Employee = new Employee() 
            };

            return View(viewModel);
        }


        [HttpGet]
        public ActionResult Ricerca()
        {
            return View();
        }


        [Authorize(Roles = "Doctor")]
        public ActionResult Contact()
        {
            return View();
        }

        [Authorize(Roles = "Pharmacist")]
        public ActionResult About()
        {
            return View();
        }
    }
}

bwFinaleVeterinaria/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

bwFinaleVeterinaria/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

bwFinaleVeterinaria/Views/Home/Index.cshtml
@model bwFinaleVeterinaria.Models.HomeView

@{
    ViewBag.Title = "Home";
}


<style>
    .btn:hover {
        background-color: #AF8771 !important;
        transition: 0.3s ease !important;
    }
</style>
<div class="container mt-5">

    @if (TempData["ErrorMessage"] != null)
    {
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            @Html.Raw(TempData["ErrorMessage"].ToString())
            <button type="button" class="btn-close" data-dismiss="alert" aria-label="Close">
            </button>
        </div>
    }




    <!-- Tabella Ammissioni -->
    <div class="mb-4 w-50 mx-auto">
        <h3 class="mb-3 fs-1 text-capitalize" style="color: #7D6151; ">Ultimi arrivati!</h3>
        <div id="rescueCarousel" class="carousel slide" data-ride="carousel" style="height: 300px; overflow: hidden;">
            <div class="carousel-inner" style="height: 100%;">
                @foreach (var item in Model.RescueAdmissions)
                {
                    <div class="carousel-item @(item == Model.RescueAdmissions.First() ? "active" : "")" style="height: 100%;">
                        <img src="@item.PetImageUrl" class="d-block w-100 h-100" alt="Immagine Animale" style="object-fit: contain; border-radius: 25px;" />
                        <div class="carousel-caption d-none d-md-block" style="position: absolute; bottom: 0; left: 0; right: 0; background-color: rgba(0,0,0,0.5); padding: 10px;">
                            <h5 style="color: white;">Data ammissione: @item.AdmissionDate</h5>
                        </div>
                    </div>
                }
            </div>
            <a class="carousel-control-prev text-decoration-none fw-bold" href="#rescueCarousel" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Precedente</span>
            </a>
            <a class="carousel-control-next text-decoration-none fw-bold" href="#rescueCarousel" role="button" data-slide="next">
                <span class="sr-only">Successivo</span>
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
            </a>
        </div>
    </div>
    <style>
        .carousel-inner {
            display: flex;
        }

        .carousel-item {
            flex: 0 0 100%;
            transition: transform 0.6s ease-in-out;
        }

            .carousel-item.active {
                transform: translateX(0);
            }

            .carousel-item-next, .carousel-item-prev, .carousel-item.active {
                display: flex;
            }

        .carousel-item-next, .carousel-item-prev {
            position: absolute;
            top: 0;
            width: 100%;
        }

        .carousel-item-next {
            transform: translateX(100%);
        }

        .carousel-item-prev {
            transform: translateX(-100%);
        }

        #rescueCarousel {
            height: 500px;
            background-color: #F7C3A1;
            border-radius: 25px;
            box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1), 0 1px 3px rgba(0, 0, 0, 0.08);
        }


        @@media (max-width: 991px) {
            #rescueCarousel {
                height: 400px;
            }
        }

        @@media (max-width: 767px) {
            #rescueCarousel {
                height: 300px;
            }
        }

        @@media (max-width: 575px) {
            #rescueCarousel {
                height: 200px;
            }
        }
    </style>
    <!-- Ricerca per Microchip -->
    <div class="mt-5">
        <div class="input-group mb-3 mt-5 d-flex justify-content-center">
            <input type="text" id="microchipInput" class="form-control" placeholder="Inserisci il numero di microchip" aria-label="Numero di Microchip" style="box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1), 0 1px 3px rgba(0, 0, 0, 0.08); " />
            <button class="btn text-white" type="button" id="searchButton" style="box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1), 0 1px 3px rgba(0, 0, 0, 0.08) ; background-color: #7D6151;">Cerca Animale</button>
        </div>
    </div>
    <!-- Info Animale -->
    <div class="pet-info-container mt-4" id="petInfo" style="display:none;">
        <div class="card" style="max-width: 540px; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1), 0 1px 3px rgba(0, 0, 0, 0.08); background-color: #F7C3A1">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src="" class="img-fluid rounded-start" id="petImage" alt="Immagine Animale">
                </div>
                <div class="col-md-8">
                    <div class="card-body" style="color: #7D6151">
                        <h5 class="card-title" style="color: #7D6151">Il tuo cucciolo è qui da noi!</h5>
                        <p class="card-text">Nome: <span id="petName"></span></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
        .pet-info-container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100%;
        }
    </style>

    <!-- Form di Login centrato -->
    <div class="m-auto w-50" style="margin-bottom: 100px!important;">
        <div class="col-12 mt-5">
            <div class=" border py-4 rounded justify-content-center" style="box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1), 0 1px 3px rgba(0, 0, 0, 0.08); background-color: #F7C3A1 ">
                <h3 class="text-center mb-4" style="color: #7D6151 ">Login Personale Medico</h3>
                @using (Html.BeginForm("Login", "Auth", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                <style>
                    .form-control:focus {
                        border-color: #7D6151 !important;
                        box-shadow: 0 0 0 0.2rem #7D6151 !important;
                    }
                </style>
                    <div class="mb-3 text-center fw-bold" style="letter-spacing: 0.3px; color: #7D6151">
                        @Html.LabelFor(m => m.Employee.Username, new { @class = "form-label" })
                        @Html.TextBoxFor(m => m.Employee.Username, new { @class = "form-control mx-auto", style = "width: auto;" })
                        @Html.ValidationMessageFor(m => m.Employee.Username, "", new { @class = "text-danger" })
                    </div>

                    <div class="mb-3 text-center fw-bold"style="letter-spacing: 0.3px; color: #7D6151">
                        @Html.LabelFor(m => m.Employee.Password, new { @class = "form-label" })
                        @Html.PasswordFor(m => m.Employee.Password, new { @class = "form-control mx-auto", style = "width: auto;" })
                        @Html.ValidationMessageFor(m => m.Employee.Password, "", new { @class = "text-danger" })
                    </div>

                    <div class="d-grid">
                        <button type="submit" class="btn text-white mx-auto" style="background-color: #7D6151;">Login</button>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section scripts {

    <script>
    $(document).ready(function() {
        $("#searchButton").click(function() {
            var microchip = $("#microchipInput").val();
            $.ajax({
                url: '@Url.Action("GetPetByMicrochip", "Api")',
                type: 'GET',
                dataType: 'json',
                data: { microchip: microchip },
                success: function(data) {
                    if(data.success) {
                        $("#petName").text(data.pet.Name);
                        if(data.pet.AdmissionInfo && data.pet.AdmissionInfo.PetImageUrl) {
                            $("#petImage").attr("src", data.pet.AdmissionInfo.PetImageUrl);
                        } else {
                            $("#petImage").attr("src", "https://media.tenor.com/sxrhvUa9VvQAAAAM/dance-till-you-are-dead-meme.gif");
                        }
                        $("#petInfo").show();
                    } else {
                        alert("Animale non trovato.");
                        $("#petInfo").hide();
                    }
                },
                error: function() {
                    alert("Si è verificato un errore nella ricerca.");
                }
            });
        });


        $(document).ready(function () {
            $('.carousel').carousel();
        });

    });
    </script>


}